### ISSUE TITLE
Docker 安装 Gitlab-CE

### ISSUE THREAD

**Issue by tvrcgo** [tvrcgo/notes#46]
## 配置

docker-compose.yaml

```yaml
version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    restart: always
    volumes:
      - ${DOCKER_HOME}/gitlab/config:/etc/gitlab
      - ${DOCKER_HOME}/gitlab/logs:/var/log/gitlab
      - ${DOCKER_HOME}/gitlab/data:/var/opt/gitlab
    ports:
      - "6443:443"
      - "6080:80"
      - "6022:22"
```

### Recipe: monitoring::grafana 阶段抛 socket.timeout 错误

![image](https://user-images.githubusercontent.com/237062/80690231-144c6300-8b01-11ea-9c02-5567966e389c.png)

卡死

![image](https://user-images.githubusercontent.com/237062/80694237-cb97a880-8b06-11ea-9a55-570f2e7db06e.png)

更新了 gitlab 镜像，继续卡死
